### ISSUE TITLE
Use the JS closure compiler instead

### ISSUE THREAD

**Issue by mattbishop** [honzabrecka/ts-to-goog#1]
There's no reason to require Java for this library: https://developers.googleblog.com/2016/08/closure-compiler-in-javascript.html

**Comment by mattbishop** [comment]
Actually this should be cljs as well! I found this library because I need a way to create closure-described JS apis from TS for uses other than cljs consumption. Ideally this could be called from node without a JVM.

**Comment by honzabrecka** [comment]
I'm afraid that as long as it's written in clojure, JVM is necessary.

Feel free to port it to cljs (node).

**Comment by mattbishop** [comment]
I guess I can't figure out why you chose jvm over js since TS->extern JS is solving a CLJS problem?

**Comment by mattbishop** [comment]
After reading the source a bit I realized now that you actually want to call tsicke _from_ the JVM. It would be good to explain why in the README.

**Comment by honzabrecka** [comment]
Updated the README, hope it's clear now. The reason why it's in clojure is that it may be used in existing tooling, which is most of the time developed in clojure and targeting JVM. Anyway I would be happy if we had javascript version published on npm which could be used in javascript world.

**Comment by mattbishop** [comment]
👍
