### ISSUE TITLE
Clarify licensing of extern files

### ISSUE THREAD

**Issue by yGuy** [honzabrecka/ts-to-goog#2]
This repository contains works derived from the contents of the definitelyTyped repository (the extern files). However most of the original files are under MIT license and copyright information as well as other licensing information from the .d.ts files have not been preserved in this repository and the new files are now being redistributed here under EPL. 

IANAL, but I don't think this is OK and indeed I do represent one such copyright holder for which in this repository there is one such derived piece of work which should not be distributed that way without being attributed, correctly. 

Please clarify that the license and copyrights in this repository only applies to the code for the converter, but not to the generated (mostly outdated anyway) extern files which have also been committed to this repository without proper attribution and copyright notice.

To make this clear: I personally have no intention to sue or whatever. I encourage you to continue your work on this and similar projects and I don't want you to take it down or change it. It's just that people have been pointing at your repo as a "proof" that our copyrighted software is actually available under terms that they have never been released under, just because they are part of this repository. A simple clarification that the files in "externs" have been taken from the definitely typed repository and that users should go there to find out more about the original licensing and the copyright holders for the respective files would be all I ask for.

Thanks!

**Comment by honzabrecka** [comment]
Hi, thanks for your comment - I removed externs folder as well as I archived the repo.
